### ISSUE TITLE
Incorrect toggling of form's save button

### ISSUE THREAD

**Issue by meixi-l** [onextech/react-hocs#1]
In an update form, the form's save button is being toggled back to false when some of fields are changed then reverted, even though there are other fields with updates in the form.

Steps to replicate: **(using Update form)**

Scenario 1 (Select Component):
1. Edit `email`
   - Save button should be enabled at this point
2. Change `country` to 'Country A'
   - Save button should remain enabled at this point
3. Change `country` back to 'Country B'
   - Save button is disabled

Scenario 2 (Checkbox Component):
1. Edit `email`
   - Save button should be enabled at this point
2. Toggle `is percentage`
   - Save button should remain enabled at this point
3. Toggle `is percentage`
   - Save button is disabled

*Note: Not sure why the `is moderator` checkbox doesn't cause the same problem*

Scenario 3 (WYSIWYG Component):
1. Edit `email`
   - Save button should be enabled at this point
2. Edit `content`
   - Save button should remain enabled at this point
3. Revert `content` back to original text
   - Save button is disabled

WORKING SCENARIO: (save button is enabled after the first field update)
1. Change `country` to 'Country A'
2. Edit `email`
3. Revert `email`

**Comment by clodal** [comment]
Fixed in ab5c6c4. Release in `0.0.55`
